### ISSUE TITLE
你好我想请问下具体流程

### ISSUE THREAD

**Issue by 1104049235** [RobbieXie/WebRTC-Classroom#14]
我这边要实现的是h5  推送webrtc 流 到 服务器  然后服务器保存webm 格式文件 在利用ffmpage 转成rtmp 推流 ，其他客户端rtmp 拉流 来实现h5 直播功能，你看我理解对吗？ 方便加个联系方式具体问下吗 我也是今天接触这块不太懂

**Comment by RobbieXie** [comment]
对的
