### ISSUE TITLE
npm ERR! socketiochat@0.0.0 start: `PORT=3000 node ./bin/www`

### ISSUE THREAD

**Issue by kevzs311** [RobbieXie/WebRTC-Classroom#9]
'PORT' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! socketiochat@0.0.0 start: `PORT=3000 node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the socketiochat@0.0.0 start script.

**Comment by RobbieXie** [comment]
maybe an error caused by node version compatible, you can try just run 'node ./bin/www'
